MySQL support
cache-rules/grice pull request #1
Opened 2017-06-20 20:54 UTC by ndenny

- Support for other SQLalchemy-supported databases
- Added requirements files
- Added support for DB URL with parameters (for unix socket support)
- Added group_by parameter

2017-06-20 23:45 UTC, cache-rules requested changes
This is great, thanks for these changes. I noted a few minor issues that should be addressed and then I will merge. Let me know if you have any questions (or disagree, open to discussion)

2017-06-20 23:45 UTC, cache-rules commented on grice/db_controller.py
> +        columns_dict = OrderedDict()
I'm assuming we're using OrderedDict here in order to basically get the functionality of a Set that preserves order, is that correct?

2017-06-20 23:45 UTC, cache-rules commented on grice/db_controller.py
> +        column_names = list(columns_dict.keys())
This can just be `list(columns_dict)`

2017-06-20 23:45 UTC, cache-rules commented on grice/db_controller.py
> +                format_as_list=request.args.get('_list', '').lower() in ['t', 'true', '1'])
Incorrect level of indent on continuation here. Also I would define a variable `format_as_list` above this and pass that in here.

2017-06-20 23:45 UTC, cache-rules commented on grice/db_service.py
> +def apply_column_groups(query, table: Table, join_table: Table, group_by: list):
I think this should be named `apply_group_by`, thoughts?

2017-06-20 23:45 UTC, cache-rules commented on grice/db_service.py
> +        # group_by_cols = names_to_columns(group_by, table, join_table) if group_by else None
This can be removed.

2017-06-20 23:45 UTC, cache-rules commented on grice/db_service.py
> +                if format_as_list:
I like this feature, good idea.

2017-06-20 23:53 UTC, ndenny commented on grice/db_controller.py
> +        columns_dict = OrderedDict()
I think I copy and pasted your code for parse_sorts for this... :) I was going to ask you why you were doing it this way... but yeah, perhaps just `set(column_names.split(',)` is all that is really required?

2017-06-20 23:56 UTC, ndenny commented on grice/db_service.py
> +def apply_column_groups(query, table: Table, join_table: Table, group_by: list):
Yeah, I'm terrible at naming things.

2017-06-21 00:01 UTC, ndenny commented on grice/db_controller.py
> +                format_as_list=request.args.get('_list', '').lower() in ['t', 'true', '1'])
NB: got a change coming where all these parameters are in one object, so we can handle POSTed JSON.

2017-06-21 00:07 UTC, ndenny commented on grice/db_controller.py
> +        columns_dict = OrderedDict()
Ah - OrderedDict.fromkeys() seems to be the thing I need.

2017-06-21 22:30 UTC, merged